export const VALID_INGREDIENTS = [
"milkshake",
"chocolate_milk",
"goat_milk_whole",
"milk_partially_skimmed",
"sour_cream",
"brown_sugar",
"powdered_sugar",
"oatmeal",
"almond_flour",
"flour",
"whole_wheat_flour",
"whole_grain_flour",
"bread_flour",
"cake_flour",
"pastry_flour",
"self_rising_flour",
"cornmeal",
"cornstarch",
"baking_powder",
"baking_soda",
"compressed_yeast",
"sourdough_starter",
"table_salt_granulated",
"sea_salt",
"gelatin",
"monosodium_glutamate",
"mustard_powdered",
"protein_supplement",
"salad_dressing",
"salt_sodium_chloride",
"salt_fine_table",
"salt_granulated",
"salt_table",
"sauce_soy",
"sodium_bicarbonate",
"vitamin_additive",
"vitamin_compound",
"vitamin_enrichment",
"vitamin_mix",
"vitamin_powder",
"yeast",
"bean_soup",
"cheddar_cheese_soup",
"chicken_noodle_soup",
"egg_drop_soup",
"mushroom_soup",
"soup_meat",
"soup_mixed",
"soup_thick_squash_potato",
"soup_vegetable",
"tomato_soup",
"glucolin_glucose",
"jam_",
"jam_sweetened",
"jelly_",
"nutella",
"sucrose",
"sucrose_octoacetate",
"sugar",
"sugar_dextrose",
"sugar_granulated",
"sugar_powdered",
"sugar_white",
"syrup_blackcurrant_undiluted",
"syrup_corn",
"syrup_corn_light",
"syrup_fruit_blackberry",
"syrup_grenadine",
"syrup_maple",
"syrup_pancake_",
"potato_chips",
"potato_chips_pringles",
"snacks_puffed_lowfat",
"blood_flour",
"blood_meal",
"bone_and_meat_meal_loose",
"bone_meal_loose",
"cow_intestine_boiled",
"cow_lean_no_bone_raw",
"cow_intestine_raw",
"goat_intestine_boiled",
"goat_intestine_raw",
"pork_fatty_with_bone_boiled",
"pork_fatty_with_bone_raw",
"pork_medium_with_bone_boiled",
"pork_medium_with_bone_raw",
"egg_yoke_powder",
"egg_chicken_boiled_poached",
"eggs_powdered",
"prawns_whole_boiled_with_shell",
"prawns_whole_boiled_without_shell",
"cinnamon_powder",
"clover_seed",
"dry_flavoring_mix_roiko_and_other_flavorings",
"garlic_flakes",
"garlic_powder",
"sage_leaves",
"spice_barbecue",
"spice_blend",
"beans_white",
"cowpeas",
"cowpeas_dried_boiled",
"cowpeas_dried_raw",
"greengram_boiled",
"greengram_raw",
"kidney_beans_dry_boiled",
"kidney_beans_dry_raw",
"kidney_beans_green_boiled",
"kidney_beans_green_raw",
"lentils_green_small_boiled",
"lentils_green_small_raw",
"pigeon_peas_boiled",
"pigeon_peas_raw",
"soybean",
"soybean_flakes",
"soybean_hulls",
"soybean_meal",
"soybean_boiled",
"soybean_boiled_with_fat",
"alfalfa_leaf_meal",
"alfalfameal_dehydrated_%",
"alfalfa_meal_dehydrated_%",
"alfalfa_meal_fine_ground",
"alfalfa_meal_suncured_%",
"alfalfa_seed",
"alfalfa_stem_meal",
"carrot_raw_chopped",
"carrot_raw_grated",
"cauliflower_boiled",
"chili_green",
"chili_red",
"french_green_beans",
"fresh_green_peas_minji",
"leaves_managu_raw_black_night_shade",
"leaves_onion_spring_onion_raw",
"corn_maize_green_sweet_corn_boiled",
"corn_maize_green_sweet_corn_raw",
"olives_green_with_stone",
"onions_chopped",
"onions_minced",
"onions_powdered",
"onions_fried_cubed",
"onions_raw_cubed",
"salad_green_leaves_raw",
"spinach_frozen_cooked",
"spinach_leaves_raw",
"sweet_pepper_raw_cubes",
"sweet_pepper_raw_half_rings",
"apple_slices_dried",
"loquat",
"paw_paw_unripe",
"almonds",
"cashews",
"coconut_chips",
"flaxseed",
"nuts",
"peanuts",
"peanuts_shelled",
"peanuts_unshelled",
"pistachio_raw_with_shell",
"pistachio_raw_without_shell",
"rapeseed",
"sunflower_seed",
"arrowroot_cocoyam_boiled",
"arrowroot_cocoyam_raw",
"cassavaflour",
"cassava_boiled",
"cassava_raw",
"potato_english_boiled",
"potato_english_raw",
"potatoes_flakes",
"potatoes_powdered",
"sweet_potato_boiled",
"sweet_potato_raw",
"yam_boiled",
"yam_raw",
"barley",
"barley_malt_flour",
"barley_fine_ground",
"barley_meal",
"barley_flour",
"barley_flour_malted_",
"barley_ground",
"barley_malted",
"barley_rolled",
"barley_scoured",
"barley_whole",
"biscuits",
"bran",
"bread",
"bread_cornbread_",
"bread_roll_soft",
"bread_white",
"bread_white_sliced_prepacked",
"breadcrumbs",
"breakfast_cereal_cornflakes_dry_cereal_",
"breakfast_cereal_muesli_w_fruits_and_nuts",
"breakfast_cereal_raisin_bran",
"breakfast_cereal_type_cheerios",
"breakfast_cereal_type_corn_flakes",
"breakfast_cereal_type_crispix",
"breakfast_cereal_type_frosted_flakes",
"breakfast_cereal_type_just_right",
"breakfast_cereal_type_rice_krispies",
"buckwheat_bran",
"buckwheat_flour",
"buckwheat_whole",
"bulrush_mille_fermented_flour",
"cake_",
"cake_mix",
"corn_maize_flour_white",
"corn_maize_starch_loosely_packed",
"corn_maize_sugar",
"corn_maize_boiled",
"corn_maize_boiled_with_fat",
"corn_maize_bran",
"corn_maize_chops_coarse",
"corn_maize_chops_fine",
"corn_maize_chops_medium",
"corn_maize_cobs",
"corn_maize_cracked_coarse",
"corn_maize_ear",
"corn_maize_fermented_flour_",
"corn_maize_flour",
"corn_maize_meal",
"corn_maize_flour_",
"corn_maize_germ_flour",
"corn_maize_gluten_flour",
"corn_maize_grits",
"corn_maize_ground",
"corn_maize_kibbled",
"corn_maize_mash",
"corn_maize_shelled",
"corn_maize_starch",
"corn_maize_starch_tightly_packed",
"corn_maize_white_boiled",
"corn_maize_white_dry",
"corn_maize_whole_kernel_dried_cracked_njenga",
"corn_maize_whole_kernel_dried_cracked_boiled_njenga",
"corn_maize_whole_shelled",
"donut_mix",
"dough_mix",
"finger_millet_fermented_flour",
"millet",
"millet_flour_bulrush",
"millet_flour_finger",
"millet_bulrush",
"millet_finger",
"oat_flour",
"oat_middlings",
"oats",
"oats_groats_whole",
"oats_ground",
"oats_hulls",
"oats_rolled",
"pasta_short_macaroni_style_boiled",
"pasta_short_macaroni_style_raw",
"pasta_noodles_boiled",
"porridge_flour_bonavist_boiled",
"porridge_flour_bonavist_raw",
"porridge_flour_ken_uji_and_lemon_extract",
"porridge_flour_ken_ujif.mill_bul_sorg_wheat",
"porridge_maize_flour_and_water",
"rice",
"rice_boiled",
"rice_boiled_with_fat",
"rice_bran",
"rice_hulled",
"rice_puffed",
"rice_raw",
"rice_rough",
"rice_white_boiled",
"rice_white_raw",
"rye",
"rye_bran",
"rye_flour_",
"rye_malted",
"rye_middlings",
"rye_shorts",
"rye_whole",
"semolina_raw",
"sorghum_fermented_flour",
"sorghum_flour",
"sorghum_seed",
"soy_flour_",
"soya_flour_",
"wheat",
"wheat_bran",
"wheat_cracked",
"wheat_cut",
"wheat_flour",
"wheat_flour_malted",
"wheat_flour_white",
"wheat_flour_wholemeal",
"wheat_gluten",
"wheat_hulls",
"wheat_middlings",
"wheat_shaved",
"wheat_whole",
"whey",
"animal_fat",
"lard",
"mayonnaise_light",
"mayonnaise_traditional",
"solid_vegetable_fat_kimbo",
"solid_vegetable_fat_rina_",
"cooking_oil_elianto_oil_salad_golden_fry_rina",
"cooking_oil_sima",
"cooking_oil_tily_chipo_pura",
"oil_cod_at_._c",
"oil_corn_at_._c",
"oil_cotton_seed_at_._c",
"oil_lard_at_._c",
"oil_linseed_at_._c",
"oil_olive_at_._c",
"oil_other_than_palmoil",
"oil_palm_at_._c",
"oil_palmoil",
"oil_peanut_at_._c",
"oil_rapeseed_at__c",
"oil_seasame_seed_at_._c",
"oil_sunflower",
"oil_vegetable_coconut",
"oil_vegetable_corn",
"oil_vegetable_olive",
"oil_vegetable_palm",
"oil_vegetable_peanut",
"oil_vegetable_soya",
"oil_whale_at_._c",
"milk_at_._c",
"milk_non_fat_dry",
"milk_powdered_whole",
"milk_powdered",
"milk_shake_fruit_and_other",
"milk_acidophilus_cultured",
"milk_buttermilk",
"milk_chocolate_milk_skimmed",
"milk_cow_whole",
"milk_evaporated",
"milk_goat_whole",
"milk_liquid_whole_semi_skimmed_skimmed",
"milk_liquid_partially_skimmed",
"milk_liquid_skimmed",
"butter",
"butter_margarine",
"buttermilk_dried",
"casein",
"cheese_emmentaler_grated",
"cream_%_fat",
"cream_%_fat",
"cream_%_fat",
"cream_double_about__%_fat",
"cream_heavy",
"cream_light",
"cream_single_about_%_fat",
"cream_sour_crème_fraiche_about_%_fat",
"cream_sour_crème_fraiche_about_%_fat",
"cream_whipped",
"cream_whipping_about_%_fat",
"ice_cream_",
"ice_cream_dairy",
"ice_cream_light_formerly_ice_milk",
"ice_cream_light_no_sugar_added",
"ice_cream_no_sugar_added",
"ice_cream_non_dairy",
"ice_cream_regular",
"ice_cream_rich",
"sour_milk_cow_whole",
"yoghurt_berry_low_fat_artificially_sweetened",
"yoghurt_fruits",
"yoghurt_low_fat_fruit",
"yoghurt_plain_unsweetened",
"yoghurt_strawberry_low_fat",
"cider_dry",
"cider_sweet",
"cider_vintage",
"wine_red",
"wine_rose_medium",
"wine_table_all",
"wine_table_red",
"wine_table_red_barbera",
"wine_table_red_burgundy",
"wine_table_red_cabernet_franc",
"wine_table_red_cabernet_sauvignon",
"wine_table_red_carignane",
"wine_table_red_claret",
"wine_table_red_gamay",
"wine_table_red_lemberger",
"wine_table_red_merlot",
"wine_table_red_mouvedre",
"wine_table_red_petite_sirah",
"wine_table_red_pinot_noir",
"wine_table_red_sangiovese",
"wine_table_red_syrah",
"wine_table_red_zinfandel",
"wine_table_white",
"wine_table_white_chardonnay",
"wine_table_white_chenin_blanc",
"wine_table_white_fume_blanc",
"wine_table_white_gewurztraminer",
"wine_table_white_late_harvest",
"wine_table_white_late_harvest_gewurztraminer",
"wine_table_white_muller_thurgau",
"wine_table_white_muscat",
"wine_table_white_pinot_blanc",
"wine_table_white_pinot_gris_grigio",
"wine_table_white_riesling",
"wine_table_white_sauvignon_blanc",
"wine_table_white_semillon",
"wine_white",
"wine_white_dry_or_sparkling",
"wine_white_medium",
"wine_white_sweet",
"alcohol_ethyl",
"amaretto",
"amaretto_di_saranno",
"anisette",
"apricot_brandy",
"apricot_liquor",
"bailey's_irish_cream",
"benedictine",
"benedictine_d.o.m.",
"blackberry_brandy",
"blackberry_liquor",
"blue_curacao",
"brandy",
"campari",
"cherry_brandy",
"cherry_liqueur",
"coffee_liquor",
"cointreau",
"crème_de_almond",
"crème_de_banana",
"crème_de_cacao",
"creme_de_cassis",
"crème_de_noyaux",
"drambuie",
"frangelico",
"galliano",
"green_chartreuse",
"green_crème_de_menthe",
"kummel",
"liqueur",
"liqueur_type_advocaat",
"liqueur_type_cherry_brandy",
"liqueur_type_curacao",
"midori_melon_liquor",
"orange_curacao",
"parfrait_d'amour",
"peach_brandy",
"peach_liqueur",
"peppermint_schnapps",
"port",
"rock_and_rye",
"sherry_dry",
"sherry_medium",
"sherry_sweet",
"sloe_gin",
"southern_comfort",
"spirits_%_alcohol",
"spirits_%_alcohol_whiskey",
"spirits_%_alcohol",
"spirits_%_alcohol",
"strawberry_liqueur",
"tia_maria",
"triple_sec",
"tuaca",
"vermouth_dry",
"vermouth_sweet",
"white_crème_de_cacao",
"white_crème_de_menthe",
"yellow_chartreuse",
"beer_lager",
"beer_light",
"beer_light_bud_light",
"beer_light_budweiser_select",
"beer_light_michelob_ultra",
"beer_local_non_specific",
"beer_pale_ale",
"beer_pilsner",
"beer_pilsner__degree_c",
"beer_regular_all",
"beer_regular_budweiser",
"beer_stout_bottled",
"beer_stout_extra",
"beer_strong_ale",
"beer_type_bitter_or_brown_ale",
"beer_type_draught",
"beer_type_keg",
"beer_type_mild_draught",
"coffee_brewed",
"coffee_expresso",
"coffee_green_beans",
"coffee_powder_nescafé",
"coffee_roasted_beans",
"miso_broth_ready_to_drink",
"powder_chocolate_drinking_powder",
"powders",
"tea_black_tea_leaves",
"tea_herbal_ciakimora_leaves_and_water",
"tea_herbal_ciakimora_leaves_",
"tea_flakes",
"tea_powdered",
"tea_liquid",
"tea_only_tea_leaves_and_water",
"tea_ready_to_drink_arizona_iced_tea_with_lemon_flavor",
"tea_ready_to_drink_lipton_brisk_iced_tea_with_lemon_flavor",
"tea_ready_to_drink_nestle_cool_nestea_ice_tea_lemon_flavor",
"apple_juice_canned_or_bottled_unsweetened_with_added_ascorbic_acid",
"apple_juice_canned_or_bottled_unsweetened_without_added_ascorbic_acid",
"beverages_fruit_juice_drink_reduced_sugar_with_vitamin_e_added",
"carbonated_beverage_tonic_water",
"cranberry_juice_cocktail_bottled",
"cranberry_apple_juice_drink_bottled",
"fruit_drinks_low_calories_undiluted",
"fruit_drinks_undiluted",
"fruit_juice",
"fruit_juice_drinks_ready_to_drink",
"grape_juice",
"grape_juice_canned_or_bottled_unsweetened_with_added_ascorbic_acid",
"grape_juice_canned_or_bottled_unsweetened_without_added_ascorbic_acid",
"guanabana_nectar_canned",
"guava_nectar_canned",
"ice_crushed",
"juice_apple_and_grape_blend_with_added_ascorbic_acid",
"juice_apple_grape_and_pear_blend_with_added_ascorbic_acid_and_calcium",
"lemonade_frozen_concentrate_pink",
"lemonade_frozen_concentrate_white",
"lime_juice_cordial_undiluted",
"mango_nectar_canned",
"meal_supplement_drink_nestle_supligen_canned_peanut_flavor",
"orange_juice",
"orange_juice_with_calcium",
"orange_juice_canned_unsweetened",
"orange_soda_sweetened_with_sugar",
"quaker_oats_propel_fitness_water_fruit_flavored_non_carbonated",
"soft_drinks_cola_type",
"soft_drinks_diet_soda",
"soft_drinks_lemonade_type",
"soft_drinks_lucozade_type",
"soy_drink",
"soya_and_milk_and_sugar",
"soya_and_sugar",
"sports_drink_coca_cola_powerade_lemon_lime_flavored_ready_to_drink",
"sports_drink_pepsico_quaker_gatorade_gatorade_original_fruit_flavored_ready_to_drink",
"tamarind_nectar_canned",
"water",
"water_ice__degree_c",
"water_ice__degree_c",
"water_liquid__degree_c",
"water_mineralwater",
];

// Create a Set for O() lookup performance
export const VALID_INGREDIENTS_SET = new Set(VALID_INGREDIENTS);

// Common ingredient mappings
export const INGREDIENT_MAPPINGS = {
  // Flours
  "all purpose flour": "flour",
  "ap flour": "flour",
  "plain flour": "flour",
  "white flour": "flour",
  "bread flour": "bread_flour",
  "cake flour": "cake_flour",
  "pastry flour": "pastry_flour",
  "self rising flour": "self_rising_flour",
  "self-rising flour": "self_rising_flour",
  "whole wheat flour": "whole_wheat_flour",
  "wholewheat flour": "whole_wheat_flour",
  
  // Sugars
  "sugar": "sugar",
  "white sugar": "sugar_white",
  "granulated sugar": "sugar_granulated",
  "caster sugar": "sugar_granulated",
  "brown sugar": "brown_sugar",
  "light brown sugar": "brown_sugar",
  "dark brown sugar": "brown_sugar",
  "powdered sugar": "powdered_sugar",
  "confectioners sugar": "powdered_sugar",
  "icing sugar": "powdered_sugar",
  
  // Salt
  "salt": "table_salt_granulated",
  "table salt": "table_salt_granulated",
  "sea salt": "sea_salt",
  "kosher salt": "salt_granulated",
  
  // Dairy
  "milk": "milk_cow_whole",
  "whole milk": "milk_cow_whole",
  "skim milk": "milk_liquid_skimmed",
  "skimmed milk": "milk_liquid_skimmed",
  "butter": "butter",
  "cream": "cream_heavy",
  "heavy cream": "cream_heavy",
  "whipping cream": "cream_whipping_about_40%_fat",
  "sour cream": "sour_cream",
  
  // Oils
  "oil": "cooking_oil_elianto_oil_salad_golden_fry_rina",
  "vegetable oil": "oil_vegetable_soya",
  "olive oil": "oil_olive_at_15.6_c",
  "coconut oil": "oil_vegetable_coconut",
  "corn oil": "oil_corn_at_15.6_c",
  
  // Common ingredients
  "water": "water",
  "eggs": "eggs_powdered",
  "egg": "eggs_powdered",
  "honey": "syrup_fruit_blackberry", // No direct honey, using closest
  "vanilla": "dry_flavoring_mix_roiko_and_other_flavorings",
  "chocolate": "chocolate_milk", // For chocolate-based recipes
  
  // Grains
  "rice": "rice",
  "white rice": "rice_white_raw",
  "brown rice": "rice_raw",
  "oats": "oats",
  "oatmeal": "oatmeal",
  
  // Baking
  "baking powder": "baking_powder",
  "baking soda": "baking_soda",
  "yeast": "yeast",
  "cornstarch": "cornstarch",
  "corn starch": "cornstarch",
  
  // Vegetables
  "onion": "onions_raw_cubed",
  "onions": "onions_raw_cubed",
  "garlic": "garlic_powder",
  "carrot": "carrot_raw_chopped",
  "carrots": "carrot_raw_chopped",
  
  // Nuts
  "almonds": "almonds",
  "almond": "almonds",
  "peanuts": "peanuts",
  "peanut": "peanuts",
  "cashews": "cashews",
  "cashew": "cashews",
};

export function findBestIngredientMatch(input) {
  const normalized = input.toLowerCase().trim();
  
  // 1. Check direct mappings first
  if (INGREDIENT_MAPPINGS[normalized]) {
    return INGREDIENT_MAPPINGS[normalized];
  }
  
  // 2. Check if it's already a valid ingredient
  const underscored = normalized.replace(/\s+/g, '_');
  if (VALID_INGREDIENTS_SET.has(underscored)) {
    return underscored;
  }
  
  // 3. Try fuzzy matching
  const matches = findFuzzyMatches(normalized);
  if (matches.length > 0) {
    return matches[0].ingredient;
  }
  
  // 4. Default transformation
  return underscored;
}

export function findFuzzyMatches(input, maxResults = 5) {
  const normalized = input.toLowerCase().trim();
  const results = [];
  
  for (const ingredient of VALID_INGREDIENTS) {
    const score = calculateSimilarity(normalized, ingredient);
    if (score > 0.5) { // Threshold for relevance
      results.push({ ingredient, score });
    }
  }
  
  return results
    .sort((a, b) => b.score - a.score)
    .slice(0, maxResults);
}

function calculateSimilarity(str1, str2) {
  const s1 = str1.replace(/_/g, ' ');
  const s2 = str2.replace(/_/g, ' ');
  
  // Check if one string contains the other
  if (s1.includes(s2) || s2.includes(s1)) {
    return 0.8;
  }
  
  // Levenshtein distance-based similarity
  const maxLen = Math.max(s1.length, s2.length);
  if (maxLen === 0) return 1.0;
  
  const distance = levenshteinDistance(s1, s2);
  return 1 - (distance / maxLen);
}

function levenshteinDistance(str1, str2) {
  const matrix = [];
  
  for (let i = 0; i <= str2.length; i++) {
    matrix[i] = [i];
  }
  
  for (let j = 0; j <= str1.length; j++) {
    matrix[0][j] = j;
  }
  
  for (let i = 1; i <= str2.length; i++) {
    for (let j = 1; j <= str1.length; j++) {
      if (str2.charAt(i - 1) === str1.charAt(j - 1)) {
        matrix[i][j] = matrix[i - 1][j - 1];
      } else {
        matrix[i][j] = Math.min(
          matrix[i - 1][j - 1] + 1,
          matrix[i][j - 1] + 1,
          matrix[i - 1][j] + 1
        );
      }
    }
  }
  
  return matrix[str2.length][str1.length];
}

export function getIngredientSuggestions(partial) {
  const normalized = partial.toLowerCase().trim();
  const suggestions = [];
  
  // Check mappings first
  for (const [common, api] of Object.entries(INGREDIENT_MAPPINGS)) {
    if (common.startsWith(normalized)) {
      suggestions.push({ display: common, value: api });
    }
  }
  
  // Then check valid ingredients
  for (const ingredient of VALID_INGREDIENTS) {
    const readable = ingredient.replace(/_/g, ' ');
    if (readable.startsWith(normalized) && suggestions.length < 10) {
      suggestions.push({ display: readable, value: ingredient });
    }
  }
  
  return suggestions.slice(0, 10);
}